system "LLM Pretraining Loop" : Concrete/Technical
domain "machine learning: next-token language model training"
component DataLoader primitive Buffering interface description "Samples and batches sequences from the corpus."
component Tokenizer primitive Splitting description "Splits raw text into subword token ids."
component Model interface description "The transformer network: embedding, stacked attention/feedforward blocks, and an unembedding head producing p(x_t | x_1..x_{t-1}) for each position t."
component LossComputation primitive Combining description "Combines predicted distribution with the true next token to score the fit."
component Optimizer description "Gradient-descent optimizer with momentum and adaptive learning rate (e.g. Adam); maintains its own running state across steps."
component Checkpointer primitive Buffering interface description "Periodically serializes model weights to durable storage."
component "Compute Cluster" interface description "Accelerators (GPUs/TPUs), interconnect, and memory hierarchy executing forward and backward passes."
source "Text Corpus"
source "Power Grid"
sink "Model Registry"
sink "Data Center Cooling"
flow "Text Corpus" -> DataLoader : informational "raw text" description "Large-scale web, book, and code corpus sampled into training batches."
flow DataLoader -> Tokenizer : informational "text batch"
flow Tokenizer -> Model : informational "token ids"
flow Model -> LossComputation : informational "predicted probs" description "Model emits p(x_t | x_1..x_{t-1}) at each position t in the sequence."
flow LossComputation -> Optimizer : informational "gradients" description "Backpropagation through L = -sum_t log p(x_t | x_1..x_{t-1}) yields gradients with respect to all parameters."
flow Optimizer -> Model : informational "weight update" description "Applies one gradient-descent step, closing the training loop."
flow Model -> Checkpointer : informational "model weights"
flow Checkpointer -> "Model Registry" : informational "checkpoint"
flow "Power Grid" -> "Compute Cluster" : energy "electricity"
flow "Compute Cluster" -> Model : energy "compute cycles" mere description "The cluster is the physical substrate executing every logical component; this is a support relation, not a data bond."
flow "Compute Cluster" -> "Data Center Cooling" : energy "waste heat"
@lens mobus