#!/bin/bash
# Assembles the facets.systems site and pushes it to the `live` branch, which
# GitHub Pages serves. Publishing is DELIBERATE (branded-surface policy: no
# auto-publish from a working branch) — running this script IS the publish.
#
#   scripts/publish-site.sh               portal + chat; Model door "coming soon"
#   scripts/publish-site.sh --with-model  + the /model/ canvas build, door open
#   scripts/publish-site.sh --dry-run     assemble only (tree left in _site/), no push
#
# Site layout:  /  portal · /chat/ chat client · /model/ canvas (wasm) · 404.html
# The live branch is a snapshot (orphan commit, force-push) — never hand-edit it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KERNEL_DIR="$REPO_ROOT/crates/bert-lenses-kernel"
WEB_DIR="$REPO_ROOT/web"
SITE_DIR="$REPO_ROOT/_site"
DOMAIN="facets.systems"

WITH_MODEL=0
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --with-model) WITH_MODEL=1 ;;
    --dry-run) DRY_RUN=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

if [ $WITH_MODEL -eq 1 ]; then
  echo "==> Building wasm kernel"
  (cd "$KERNEL_DIR" && wasm-pack build --target web --out-dir pkg)
  echo "==> Building web frontend at base /model/"
  (cd "$WEB_DIR" && npm install && VITE_BASE=/model/ npm run build)
fi

echo "==> Assembling site tree"
rm -rf "$SITE_DIR"
mkdir -p "$SITE_DIR"
cp "$REPO_ROOT/portal/index.html" "$SITE_DIR/index.html"
rsync -a --exclude docs "$REPO_ROOT/chat/" "$SITE_DIR/chat/"
mv "$SITE_DIR/chat/404.html" "$SITE_DIR/404.html"   # Pages serves one 404 per site
echo "$DOMAIN" > "$SITE_DIR/CNAME"
if [ $WITH_MODEL -eq 1 ]; then
  rsync -a "$WEB_DIR/dist/" "$SITE_DIR/model/"
  sed -i '' 's/var MODEL_LIVE = false;/var MODEL_LIVE = true;/' "$SITE_DIR/index.html"
fi

if [ $DRY_RUN -eq 1 ]; then
  echo "==> Dry run: tree assembled at $SITE_DIR (not pushed)"
  exit 0
fi

echo "==> Publishing snapshot to origin/live"
SHA=$(git -C "$REPO_ROOT" rev-parse --short HEAD)
TMP_INDEX=$(mktemp)
trap 'rm -f "$TMP_INDEX"' EXIT
# Build the snapshot commit with a scratch index so the session's working index
# is never touched (one repo, one index — parallel worktrees are live here).
TREE=$(cd "$SITE_DIR" && GIT_DIR="$REPO_ROOT/.git" GIT_INDEX_FILE="$TMP_INDEX" \
  git add -Af . >/dev/null && GIT_DIR="$REPO_ROOT/.git" GIT_INDEX_FILE="$TMP_INDEX" \
  git write-tree)
MODEL_NOTE=$([ $WITH_MODEL -eq 1 ] && echo "with model" || echo "model dark")
COMMIT=$(GIT_DIR="$REPO_ROOT/.git" git commit-tree "$TREE" \
  -m "site snapshot from $SHA ($MODEL_NOTE) — generated by publish-site.sh, never hand-edit")
git -C "$REPO_ROOT" push --force origin "$COMMIT:refs/heads/live"
echo "==> Live: https://$DOMAIN (snapshot $COMMIT from $SHA, $MODEL_NOTE)"
