#!/usr/bin/env python3
"""Vendor the three UI faces into web/src/fonts/ and regenerate web/src/fonts.css.

The app must not depend on fonts.googleapis.com: the desktop build runs from
tauri://localhost with no network, and a served build should render the same
offline. So the woff2 files live in the repo and index.css imports fonts.css.

Google serves one full-axis variable file per family+subset regardless of the
weights the css2 query names (every weight URL returns the same bytes), so each
face is declared once over its real wght axis. Declaring only the used weights
would make the browser synthesize anything outside them.

Run from anywhere: python3 scripts/vendor-fonts.py
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "web" / "src" / "fonts"
OUT_CSS = ROOT / "web" / "src" / "fonts.css"

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Cormorant+Garamond:wght@500;600"
    "&family=Inter:wght@400;500;600"
    "&family=JetBrains+Mono:wght@400;500"
    "&display=swap"
)
# css2 keys the response off the UA; a Safari UA gets woff2 rather than ttf.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 "
    "(KHTML, like Gecko) Version/17.0 Safari/605.1.15"
)

SUBSETS = ("latin", "latin-ext")
SLUG = {
    "Cormorant Garamond": "cormorant-garamond",
    "Inter": "inter",
    "JetBrains Mono": "jetbrains-mono",
}
# wght axis of each downloaded file, read from its fvar table.
AXIS = {
    "Cormorant Garamond": (300, 700),
    "Inter": (100, 900),
    "JetBrains Mono": (400, 800),
}


def fetch(url: str, dest: Path | None = None) -> bytes:
    cmd = ["curl", "-sSf", "-H", f"User-Agent: {UA}", url]
    if dest:
        cmd += ["-o", str(dest)]
        subprocess.run(cmd, check=True)
        return b""
    return subprocess.run(cmd, check=True, capture_output=True).stdout


def main() -> int:
    css = fetch(CSS_URL).decode()
    faces: dict[tuple[str, str], dict] = {}
    for subset, block in re.findall(r"/\* (\S+) \*/\n(@font-face \{.*?\n\})", css, re.S):
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        entry = faces.setdefault((family, subset), {})
        entry["url"] = re.search(r"url\((\S+?)\)", block).group(1)
        entry["range"] = re.search(r"unicode-range: ([^;]+);", block).group(1)

    missing = set(SLUG) - {family for family, _ in faces}
    if missing:
        print(f"css2 response is missing {sorted(missing)}", file=sys.stderr)
        return 1

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Self-hosted UI faces (SIL OFL 1.1, see fonts/OFL.txt). Generated by",
        "   scripts/vendor-fonts.py — edit that, not this. Vendored so the desktop",
        "   app and any offline session render identically to the served build: no",
        "   fonts.googleapis.com <link>, no remote dependency. All three families",
        "   are variable, hence one file per subset over a wght range. */",
        "",
    ]
    for (family, subset), entry in sorted(faces.items()):
        name = f"{SLUG[family]}-{subset}.woff2"
        dest = FONT_DIR / name
        fetch(entry["url"], dest)
        lo, hi = AXIS[family]
        print(f"{name}  {dest.stat().st_size} bytes  wght {lo}-{hi}")
        lines += [
            "@font-face {",
            f'  font-family: "{family}";',
            "  font-style: normal;",
            f"  font-weight: {lo} {hi};",
            "  font-display: swap;",
            f'  src: url("./fonts/{name}") format("woff2");',
            f"  unicode-range: {entry['range']};",
            "}",
            "",
        ]
    OUT_CSS.write_text("\n".join(lines))
    print(f"{OUT_CSS.relative_to(ROOT)}: {len(faces)} faces")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
